name: Udacity CICD Project - CI with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        make setup
        make install
        wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
        chmod +x /bin/hadolint
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test